    - name: Selenium Preparation
      run: docker run --network=isolated -d -p 4444:4444 -p 7900:7900 \
           -v /dev/shm:/dev/shm \
           --name firefox-standalone selenium/standalone-firefox:latest

    - name: Wait for Selenium boot
      run: sleep 15

    - name: Make wait.sh executable
      run: chmod +x wait.sh

    - name: Wait for Selenium Hub
      run: ./wait.sh

    - name: Check the Hub
      run: curl http://localhost:4444/ui
